"""empty message

Revision ID: 2006a9946183
Revises: None
Create Date: 2015-12-21 16:58:40.503461

"""

# revision identifiers, used by Alembic.
revision = '2006a9946183'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bucketlist', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlist', type_='unique')
    ### end Alembic commands ###
